# Generated by Django 5.1.6 on 2025-03-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
