# Generated by Django 5.1.6 on 2025-03-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tagspage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
